steps:


- name: gcr.io/cloud-builders/dotnet
  args: [build]
  dir: 'stockpred/'
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', '/var/www/html', 'gs://$PROJECT_ID/stock-123']

images:

- gcr.io/$PROJECT_ID/stack
